name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2 
      - run: |
           pip install poetry
           poetry install
      - run: |
           make lint


